export default [{
		value: "北京",
		text: "北京",
		children: [{
			value: "东城",
			text: "东城",
			zipcode: "110101"
		}, {
			value: "西城",
			text: "西城",
			zipcode: "110102"
		}, {
			value: "崇文",
			text: "崇文",
			zipcode: "110103"
		}, {
			value: "宣武",
			text: "宣武",
			zipcode: "110104"
		}, {
			value: "朝阳",
			text: "朝阳",
			zipcode: "110105"
		}, {
			value: "丰台",
			text: "丰台",
			zipcode: "110106"
		}, {
			value: "石景山",
			text: "石景山",
			zipcode: "110107"
		}, {
			value: "海淀",
			text: "海淀",
			zipcode: "110108"
		}, {
			value: "门头沟",
			text: "门头沟",
			zipcode: "110109"
		}, {
			value: "房山",
			text: "房山",
			zipcode: "110111"
		}, {
			value: "通州",
			text: "通州",
			zipcode: "110112"
		}, {
			value: "顺义",
			text: "顺义",
			zipcode: "110113"
		}, {
			value: "昌平",
			text: "昌平",
			zipcode: "110114"
		}, {
			value: "大兴",
			text: "大兴",
			zipcode: "110115"
		}, {
			value: "怀柔",
			text: "怀柔",
			zipcode: "110116"
		}, {
			value: "平谷",
			text: "平谷",
			zipcode: "110117"
		}, {
			value: "密云",
			text: "密云",
			zipcode: "110228"
		}, {
			value: "延庆",
			text: "延庆",
			zipcode: "110229"
		}],
		zipcode: "110000"
	}, {
		value: "天津",
		text: "天津",
		children: [{
			value: "和平",
			text: "和平",
			zipcode: "120101"
		}, {
			value: "河东",
			text: "河东",
			zipcode: "120102"
		}, {
			value: "河西",
			text: "河西",
			zipcode: "120103"
		}, {
			value: "南开",
			text: "南开",
			zipcode: "120104"
		}, {
			value: "河北",
			text: "河北",
			zipcode: "120105"
		}, {
			value: "红桥",
			text: "红桥",
			zipcode: "120106"
		}, {
			value: "塘沽",
			text: "塘沽",
			zipcode: "120107"
		}, {
			value: "汉沽",
			text: "汉沽",
			zipcode: "120108"
		}, {
			value: "大港",
			text: "大港",
			zipcode: "120109"
		}, {
			value: "东丽",
			text: "东丽",
			zipcode: "120110"
		}, {
			value: "西青",
			text: "西青",
			zipcode: "120111"
		}, {
			value: "津南",
			text: "津南",
			zipcode: "120112"
		}, {
			value: "北辰",
			text: "北辰",
			zipcode: "120113"
		}, {
			value: "武清",
			text: "武清",
			zipcode: "120114"
		}, {
			value: "宝坻",
			text: "宝坻",
			zipcode: "120115"
		}, {
			value: "滨海新区",
			text: "滨海新区",
			zipcode: "120116"
		}, {
			value: "宁河",
			text: "宁河",
			zipcode: "120221"
		}, {
			value: "静海",
			text: "静海",
			zipcode: "120223"
		}, {
			value: "蓟县",
			text: "蓟县",
			zipcode: "120225"
		}],
		zipcode: "120000"
	}, {
		value: "河北",
		text: "河北",
		children: [{
			value: "石家庄",
			text: "石家庄",
			zipcode: "130100"
		}, {
			value: "唐山",
			text: "唐山",
			zipcode: "130200"
		}, {
			value: "秦皇岛",
			text: "秦皇岛",
			zipcode: "130300"
		}, {
			value: "邯郸",
			text: "邯郸",
			zipcode: "130400"
		}, {
			value: "邢台",
			text: "邢台",
			zipcode: "130500"
		}, {
			value: "保定",
			text: "保定",
			zipcode: "130600"
		}, {
			value: "张家口",
			text: "张家口",
			zipcode: "130700"
		}, {
			value: "承德",
			text: "承德",
			zipcode: "130800"
		}, {
			value: "沧州",
			text: "沧州",
			zipcode: "130900"
		}, {
			value: "廊坊",
			text: "廊坊",
			zipcode: "131000"
		}, {
			value: "衡水",
			text: "衡水",
			zipcode: "131100"
		}],
		zipcode: "130000"
	}, {
		value: "山西",
		text: "山西",
		children: [{
			value: "太原",
			text: "太原",
			zipcode: "140100"
		}, {
			value: "大同",
			text: "大同",
			zipcode: "140200"
		}, {
			value: "阳泉",
			text: "阳泉",
			zipcode: "140300"
		}, {
			value: "长治",
			text: "长治",
			zipcode: "140400"
		}, {
			value: "晋城",
			text: "晋城",
			zipcode: "140500"
		}, {
			value: "朔州",
			text: "朔州",
			zipcode: "140600"
		}, {
			value: "晋中",
			text: "晋中",
			zipcode: "140700"
		}, {
			value: "运城",
			text: "运城",
			zipcode: "140800"
		}, {
			value: "忻州",
			text: "忻州",
			zipcode: "140900"
		}, {
			value: "临汾",
			text: "临汾",
			zipcode: "141000"
		}, {
			value: "吕梁",
			text: "吕梁",
			zipcode: "141100"
		}],
		zipcode: "140000"
	}, {
		value: "内蒙古",
		text: "内蒙古",
		children: [{
			value: "呼和浩特",
			text: "呼和浩特",
			zipcode: "150100"
		}, {
			value: "包头",
			text: "包头",
			zipcode: "150200"
		}, {
			value: "乌海",
			text: "乌海",
			zipcode: "150300"
		}, {
			value: "赤峰",
			text: "赤峰",
			zipcode: "150400"
		}, {
			value: "通辽",
			text: "通辽",
			zipcode: "150500"
		}, {
			value: "鄂尔多斯",
			text: "鄂尔多斯",
			zipcode: "150600"
		}, {
			value: "呼伦贝尔",
			text: "呼伦贝尔",
			zipcode: "150700"
		}, {
			value: "巴彦淖尔",
			text: "巴彦淖尔",
			zipcode: "150800"
		}, {
			value: "乌兰察布",
			text: "乌兰察布",
			zipcode: "150900"
		}, {
			value: "兴安",
			text: "兴安",
			zipcode: "152200"
		}, {
			value: "锡林郭勒",
			text: "锡林郭勒",
			zipcode: "152500"
		}, {
			value: "阿拉善",
			text: "阿拉善",
			zipcode: "152900"
		}],
		zipcode: "150000"
	}, {
		value: "辽宁",
		text: "辽宁",
		children: [{
			value: "沈阳",
			text: "沈阳",
			zipcode: "210100"
		}, {
			value: "大连",
			text: "大连",
			zipcode: "210200"
		}, {
			value: "鞍山",
			text: "鞍山",
			zipcode: "210300"
		}, {
			value: "抚顺",
			text: "抚顺",
			zipcode: "210400"
		}, {
			value: "本溪",
			text: "本溪",
			zipcode: "210500"
		}, {
			value: "丹东",
			text: "丹东",
			zipcode: "210600"
		}, {
			value: "锦州",
			text: "锦州",
			zipcode: "210700"
		}, {
			value: "营口",
			text: "营口",
			zipcode: "210800"
		}, {
			value: "阜新",
			text: "阜新",
			zipcode: "210900"
		}, {
			value: "辽阳",
			text: "辽阳",
			zipcode: "211000"
		}, {
			value: "盘锦",
			text: "盘锦",
			zipcode: "211100"
		}, {
			value: "铁岭",
			text: "铁岭",
			zipcode: "211200"
		}, {
			value: "朝阳",
			text: "朝阳",
			zipcode: "211300"
		}, {
			value: "葫芦岛",
			text: "葫芦岛",
			zipcode: "211400"
		}],
		zipcode: "210000"
	}, {
		value: "吉林",
		text: "吉林",
		children: [{
			value: "长春",
			text: "长春",
			zipcode: "220100"
		}, {
			value: "吉林",
			text: "吉林",
			zipcode: "220200"
		}, {
			value: "四平",
			text: "四平",
			zipcode: "220300"
		}, {
			value: "辽源",
			text: "辽源",
			zipcode: "220400"
		}, {
			value: "通化",
			text: "通化",
			zipcode: "220500"
		}, {
			value: "白山",
			text: "白山",
			zipcode: "220600"
		}, {
			value: "松原",
			text: "松原",
			zipcode: "220700"
		}, {
			value: "白城",
			text: "白城",
			zipcode: "220800"
		}, {
			value: "延边",
			text: "延边",
			zipcode: "222400"
		}],
		zipcode: "220000"
	}, {
		value: "黑龙江",
		text: "黑龙江",
		children: [{
			value: "哈尔滨",
			text: "哈尔滨",
			zipcode: "230100"
		}, {
			value: "齐齐哈尔",
			text: "齐齐哈尔",
			zipcode: "230200"
		}, {
			value: "鸡西",
			text: "鸡西",
			zipcode: "230300"
		}, {
			value: "鹤岗",
			text: "鹤岗",
			zipcode: "230400"
		}, {
			value: "双鸭山",
			text: "双鸭山",
			zipcode: "230500"
		}, {
			value: "大庆",
			text: "大庆",
			zipcode: "230600"
		}, {
			value: "伊春",
			text: "伊春",
			zipcode: "230700"
		}, {
			value: "佳木斯",
			text: "佳木斯",
			zipcode: "230800"
		}, {
			value: "七台河",
			text: "七台河",
			zipcode: "230900"
		}, {
			value: "牡丹江",
			text: "牡丹江",
			zipcode: "231000"
		}, {
			value: "黑河",
			text: "黑河",
			zipcode: "231100"
		}, {
			value: "绥化",
			text: "绥化",
			zipcode: "231200"
		}, {
			value: "大兴安岭",
			text: "大兴安岭",
			zipcode: "232700"
		}],
		zipcode: "230000"
	}, {
		value: "上海",
		text: "上海",
		children: [{
			value: "黄浦",
			text: "黄浦",
			zipcode: "310101"
		}, {
			value: "卢湾",
			text: "卢湾",
			zipcode: "310103"
		}, {
			value: "徐汇",
			text: "徐汇",
			zipcode: "310104"
		}, {
			value: "长宁",
			text: "长宁",
			zipcode: "310105"
		}, {
			value: "静安",
			text: "静安",
			zipcode: "310106"
		}, {
			value: "普陀",
			text: "普陀",
			zipcode: "310107"
		}, {
			value: "闸北",
			text: "闸北",
			zipcode: "310108"
		}, {
			value: "虹口",
			text: "虹口",
			zipcode: "310109"
		}, {
			value: "杨浦",
			text: "杨浦",
			zipcode: "310110"
		}, {
			value: "闵行",
			text: "闵行",
			zipcode: "310112"
		}, {
			value: "宝山",
			text: "宝山",
			zipcode: "310113"
		}, {
			value: "嘉定",
			text: "嘉定",
			zipcode: "310114"
		}, {
			value: "浦东新区",
			text: "浦东新区",
			zipcode: "310115"
		}, {
			value: "金山",
			text: "金山",
			zipcode: "310116"
		}, {
			value: "松江",
			text: "松江",
			zipcode: "310117"
		}, {
			value: "青浦",
			text: "青浦",
			zipcode: "310118"
		}, {
			value: "南汇",
			text: "南汇",
			zipcode: "310119"
		}, {
			value: "奉贤",
			text: "奉贤",
			zipcode: "310120"
		}, {
			value: "川沙",
			text: "川沙",
			zipcode: "310152"
		}, {
			value: "崇明",
			text: "崇明",
			zipcode: "310230"
		}],
		zipcode: "310000"
	}, {
		value: "江苏",
		text: "江苏",
		children: [{
			value: "南京",
			text: "南京",
			zipcode: "320100"
		}, {
			value: "无锡",
			text: "无锡",
			zipcode: "320200"
		}, {
			value: "徐州",
			text: "徐州",
			zipcode: "320300"
		}, {
			value: "常州",
			text: "常州",
			zipcode: "320400"
		}, {
			value: "苏州",
			text: "苏州",
			zipcode: "320500"
		}, {
			value: "南通",
			text: "南通",
			zipcode: "320600"
		}, {
			value: "连云港",
			text: "连云港",
			zipcode: "320700"
		}, {
			value: "淮安",
			text: "淮安",
			zipcode: "320800"
		}, {
			value: "盐城",
			text: "盐城",
			zipcode: "320900"
		}, {
			value: "扬州",
			text: "扬州",
			zipcode: "321000"
		}, {
			value: "镇江",
			text: "镇江",
			zipcode: "321100"
		}, {
			value: "泰州",
			text: "泰州",
			zipcode: "321200"
		}, {
			value: "宿迁",
			text: "宿迁",
			zipcode: "321300"
		}],
		zipcode: "320000"
	}, {
		value: "浙江",
		text: "浙江",
		children: [{
			value: "杭州",
			text: "杭州",
			zipcode: "330100"
		}, {
			value: "宁波",
			text: "宁波",
			zipcode: "330200"
		}, {
			value: "温州",
			text: "温州",
			zipcode: "330300"
		}, {
			value: "嘉兴",
			text: "嘉兴",
			zipcode: "330400"
		}, {
			value: "湖州",
			text: "湖州",
			zipcode: "330500"
		}, {
			value: "绍兴",
			text: "绍兴",
			zipcode: "330600"
		}, {
			value: "金华",
			text: "金华",
			zipcode: "330700"
		}, {
			value: "衢州",
			text: "衢州",
			zipcode: "330800"
		}, {
			value: "舟山",
			text: "舟山",
			zipcode: "330900"
		}, {
			value: "台州",
			text: "台州",
			zipcode: "331000"
		}, {
			value: "丽水",
			text: "丽水",
			zipcode: "331100"
		}],
		zipcode: "330000"
	}, {
		value: "安徽",
		text: "安徽",
		children: [{
			value: "合肥",
			text: "合肥",
			zipcode: "340100"
		}, {
			value: "芜湖",
			text: "芜湖",
			zipcode: "340200"
		}, {
			value: "蚌埠",
			text: "蚌埠",
			zipcode: "340300"
		}, {
			value: "淮南",
			text: "淮南",
			zipcode: "340400"
		}, {
			value: "马鞍山",
			text: "马鞍山",
			zipcode: "340500"
		}, {
			value: "淮北",
			text: "淮北",
			zipcode: "340600"
		}, {
			value: "铜陵",
			text: "铜陵",
			zipcode: "340700"
		}, {
			value: "安庆",
			text: "安庆",
			zipcode: "340800"
		}, {
			value: "黄山",
			text: "黄山",
			zipcode: "341000"
		}, {
			value: "滁州",
			text: "滁州",
			zipcode: "341100"
		}, {
			value: "阜阳",
			text: "阜阳",
			zipcode: "341200"
		}, {
			value: "宿州",
			text: "宿州",
			zipcode: "341300"
		}, {
			value: "六安",
			text: "六安",
			zipcode: "341500"
		}, {
			value: "亳州",
			text: "亳州",
			zipcode: "341600"
		}, {
			value: "池州",
			text: "池州",
			zipcode: "341700"
		}, {
			value: "宣城",
			text: "宣城",
			zipcode: "341800"
		}],
		zipcode: "340000"
	}, {
		value: "福建",
		text: "福建",
		children: [{
			value: "福州",
			text: "福州",
			zipcode: "350100"
		}, {
			value: "厦门",
			text: "厦门",
			zipcode: "350200"
		}, {
			value: "莆田",
			text: "莆田",
			zipcode: "350300"
		}, {
			value: "三明",
			text: "三明",
			zipcode: "350400"
		}, {
			value: "泉州",
			text: "泉州",
			zipcode: "350500"
		}, {
			value: "漳州",
			text: "漳州",
			zipcode: "350600"
		}, {
			value: "南平",
			text: "南平",
			zipcode: "350700"
		}, {
			value: "龙岩",
			text: "龙岩",
			zipcode: "350800"
		}, {
			value: "宁德",
			text: "宁德",
			zipcode: "350900"
		}],
		zipcode: "350000"
	}, {
		value: "江西",
		text: "江西",
		children: [{
			value: "南昌",
			text: "南昌",
			zipcode: "360100"
		}, {
			value: "景德镇",
			text: "景德镇",
			zipcode: "360200"
		}, {
			value: "萍乡",
			text: "萍乡",
			zipcode: "360300"
		}, {
			value: "九江",
			text: "九江",
			zipcode: "360400"
		}, {
			value: "新余",
			text: "新余",
			zipcode: "360500"
		}, {
			value: "鹰潭",
			text: "鹰潭",
			zipcode: "360600"
		}, {
			value: "赣州",
			text: "赣州",
			zipcode: "360700"
		}, {
			value: "吉安",
			text: "吉安",
			zipcode: "360800"
		}, {
			value: "宜春",
			text: "宜春",
			zipcode: "360900"
		}, {
			value: "抚州",
			text: "抚州",
			zipcode: "361000"
		}, {
			value: "上饶",
			text: "上饶",
			zipcode: "361100"
		}],
		zipcode: "360000"
	}, {
		value: "山东",
		text: "山东",
		children: [{
			value: "济南",
			text: "济南",
			zipcode: "370100"
		}, {
			value: "青岛",
			text: "青岛",
			zipcode: "370200"
		}, {
			value: "淄博",
			text: "淄博",
			zipcode: "370300"
		}, {
			value: "枣庄",
			text: "枣庄",
			zipcode: "370400"
		}, {
			value: "东营",
			text: "东营",
			zipcode: "370500"
		}, {
			value: "烟台",
			text: "烟台",
			zipcode: "370600"
		}, {
			value: "潍坊",
			text: "潍坊",
			zipcode: "370700"
		}, {
			value: "济宁",
			text: "济宁",
			zipcode: "370800"
		}, {
			value: "泰安",
			text: "泰安",
			zipcode: "370900"
		}, {
			value: "威海",
			text: "威海",
			zipcode: "371000"
		}, {
			value: "日照",
			text: "日照",
			zipcode: "371100"
		}, {
			value: "莱芜",
			text: "莱芜",
			zipcode: "371200"
		}, {
			value: "临沂",
			text: "临沂",
			zipcode: "371300"
		}, {
			value: "德州",
			text: "德州",
			zipcode: "371400"
		}, {
			value: "聊城",
			text: "聊城",
			zipcode: "371500"
		}, {
			value: "滨州",
			text: "滨州",
			zipcode: "371600"
		}, {
			value: "菏泽",
			text: "菏泽",
			zipcode: "371700"
		}],
		zipcode: "370000"
	}, {
		value: "河南",
		text: "河南",
		children: [{
			value: "郑州",
			text: "郑州",
			zipcode: "410100"
		}, {
			value: "开封",
			text: "开封",
			zipcode: "410200"
		}, {
			value: "洛阳",
			text: "洛阳",
			zipcode: "410300"
		}, {
			value: "平顶山",
			text: "平顶山",
			zipcode: "410400"
		}, {
			value: "安阳",
			text: "安阳",
			zipcode: "410500"
		}, {
			value: "鹤壁",
			text: "鹤壁",
			zipcode: "410600"
		}, {
			value: "新乡",
			text: "新乡",
			zipcode: "410700"
		}, {
			value: "焦作",
			text: "焦作",
			zipcode: "410800"
		}, {
			value: "济源",
			text: "济源",
			zipcode: "410881"
		}, {
			value: "濮阳",
			text: "濮阳",
			zipcode: "410900"
		}, {
			value: "许昌",
			text: "许昌",
			zipcode: "411000"
		}, {
			value: "漯河",
			text: "漯河",
			zipcode: "411100"
		}, {
			value: "三门峡",
			text: "三门峡",
			zipcode: "411200"
		}, {
			value: "南阳",
			text: "南阳",
			zipcode: "411300"
		}, {
			value: "商丘",
			text: "商丘",
			zipcode: "411400"
		}, {
			value: "信阳",
			text: "信阳",
			zipcode: "411500"
		}, {
			value: "周口",
			text: "周口",
			zipcode: "411600"
		}, {
			value: "驻马店",
			text: "驻马店",
			zipcode: "411700"
		}],
		zipcode: "410000"
	}, {
		value: "湖北",
		text: "湖北",
		children: [{
			value: "武汉",
			text: "武汉",
			zipcode: "420100"
		}, {
			value: "黄石",
			text: "黄石",
			zipcode: "420200"
		}, {
			value: "十堰",
			text: "十堰",
			zipcode: "420300"
		}, {
			value: "宜昌",
			text: "宜昌",
			zipcode: "420500"
		}, {
			value: "襄阳",
			text: "襄阳",
			zipcode: "420600"
		}, {
			value: "鄂州",
			text: "鄂州",
			zipcode: "420700"
		}, {
			value: "荆门",
			text: "荆门",
			zipcode: "420800"
		}, {
			value: "孝感",
			text: "孝感",
			zipcode: "420900"
		}, {
			value: "荆州",
			text: "荆州",
			zipcode: "421000"
		}, {
			value: "黄冈",
			text: "黄冈",
			zipcode: "421100"
		}, {
			value: "咸宁",
			text: "咸宁",
			zipcode: "421200"
		}, {
			value: "随州",
			text: "随州",
			zipcode: "421300"
		}, {
			value: "恩施",
			text: "恩施",
			zipcode: "422800"
		}, {
			value: "仙桃",
			text: "仙桃",
			zipcode: "429004"
		}, {
			value: "潜江",
			text: "潜江",
			zipcode: "429005"
		}, {
			value: "天门",
			text: "天门",
			zipcode: "429006"
		}, {
			value: "神农架",
			text: "神农架",
			zipcode: "429021"
		}],
		zipcode: "420000"
	}, {
		value: "湖南",
		text: "湖南",
		children: [{
			value: "长沙",
			text: "长沙",
			zipcode: "430100"
		}, {
			value: "株洲",
			text: "株洲",
			zipcode: "430200"
		}, {
			value: "湘潭",
			text: "湘潭",
			zipcode: "430300"
		}, {
			value: "衡阳",
			text: "衡阳",
			zipcode: "430400"
		}, {
			value: "邵阳",
			text: "邵阳",
			zipcode: "430500"
		}, {
			value: "岳阳",
			text: "岳阳",
			zipcode: "430600"
		}, {
			value: "常德",
			text: "常德",
			zipcode: "430700"
		}, {
			value: "张家界",
			text: "张家界",
			zipcode: "430800"
		}, {
			value: "益阳",
			text: "益阳",
			zipcode: "430900"
		}, {
			value: "郴州",
			text: "郴州",
			zipcode: "431000"
		}, {
			value: "永州",
			text: "永州",
			zipcode: "431100"
		}, {
			value: "怀化",
			text: "怀化",
			zipcode: "431200"
		}, {
			value: "娄底",
			text: "娄底",
			zipcode: "431300"
		}, {
			value: "湘西",
			text: "湘西",
			zipcode: "433100"
		}],
		zipcode: "430000"
	}, {
		value: "广东",
		text: "广东",
		children: [{
			value: "广州",
			text: "广州",
			zipcode: "440100"
		}, {
			value: "韶关",
			text: "韶关",
			zipcode: "440200"
		}, {
			value: "深圳",
			text: "深圳",
			zipcode: "440300"
		}, {
			value: "珠海",
			text: "珠海",
			zipcode: "440400"
		}, {
			value: "汕头",
			text: "汕头",
			zipcode: "440500"
		}, {
			value: "佛山",
			text: "佛山",
			zipcode: "440600"
		}, {
			value: "江门",
			text: "江门",
			zipcode: "440700"
		}, {
			value: "湛江",
			text: "湛江",
			zipcode: "440800"
		}, {
			value: "茂名",
			text: "茂名",
			zipcode: "440900"
		}, {
			value: "肇庆",
			text: "肇庆",
			zipcode: "441200"
		}, {
			value: "惠州",
			text: "惠州",
			zipcode: "441300"
		}, {
			value: "梅州",
			text: "梅州",
			zipcode: "441400"
		}, {
			value: "汕尾",
			text: "汕尾",
			zipcode: "441500"
		}, {
			value: "河源",
			text: "河源",
			zipcode: "441600"
		}, {
			value: "阳江",
			text: "阳江",
			zipcode: "441700"
		}, {
			value: "清远",
			text: "清远",
			zipcode: "441800"
		}, {
			value: "东莞",
			text: "东莞",
			zipcode: "441900"
		}, {
			value: "中山",
			text: "中山",
			zipcode: "442000"
		}, {
			value: "潮州",
			text: "潮州",
			zipcode: "445100"
		}, {
			value: "揭阳",
			text: "揭阳",
			zipcode: "445200"
		}, {
			value: "云浮",
			text: "云浮",
			zipcode: "445300"
		}],
		zipcode: "440000"
	}, {
		value: "广西",
		text: "广西",
		children: [{
			value: "南宁",
			text: "南宁",
			zipcode: "450100"
		}, {
			value: "柳州",
			text: "柳州",
			zipcode: "450200"
		}, {
			value: "桂林",
			text: "桂林",
			zipcode: "450300"
		}, {
			value: "梧州",
			text: "梧州",
			zipcode: "450400"
		}, {
			value: "北海",
			text: "北海",
			zipcode: "450500"
		}, {
			value: "防城港",
			text: "防城港",
			zipcode: "450600"
		}, {
			value: "钦州",
			text: "钦州",
			zipcode: "450700"
		}, {
			value: "贵港",
			text: "贵港",
			zipcode: "450800"
		}, {
			value: "玉林",
			text: "玉林",
			zipcode: "450900"
		}, {
			value: "百色",
			text: "百色",
			zipcode: "451000"
		}, {
			value: "贺州",
			text: "贺州",
			zipcode: "451100"
		}, {
			value: "河池",
			text: "河池",
			zipcode: "451200"
		}, {
			value: "来宾",
			text: "来宾",
			zipcode: "451300"
		}, {
			value: "崇左",
			text: "崇左",
			zipcode: "451400"
		}],
		zipcode: "450000"
	}, {
		value: "海南",
		text: "海南",
		children: [{
			value: "海口",
			text: "海口",
			zipcode: "460100"
		}, {
			value: "三亚",
			text: "三亚",
			zipcode: "460200"
		}, {
			value: "五指山",
			text: "五指山",
			zipcode: "469001"
		}, {
			value: "琼海",
			text: "琼海",
			zipcode: "469002"
		}, {
			value: "儋州",
			text: "儋州",
			zipcode: "469003"
		}, {
			value: "文昌",
			text: "文昌",
			zipcode: "469005"
		}, {
			value: "万宁",
			text: "万宁",
			zipcode: "469006"
		}, {
			value: "东方",
			text: "东方",
			zipcode: "469007"
		}, {
			value: "定安",
			text: "定安",
			zipcode: "469025"
		}, {
			value: "屯昌",
			text: "屯昌",
			zipcode: "469026"
		}, {
			value: "澄迈",
			text: "澄迈",
			zipcode: "469027"
		}, {
			value: "临高",
			text: "临高",
			zipcode: "469028"
		}, {
			value: "白沙",
			text: "白沙",
			zipcode: "469030"
		}, {
			value: "昌江",
			text: "昌江",
			zipcode: "469031"
		}, {
			value: "乐东",
			text: "乐东",
			zipcode: "469033"
		}, {
			value: "陵水",
			text: "陵水",
			zipcode: "469034"
		}, {
			value: "保亭",
			text: "保亭",
			zipcode: "469035"
		}, {
			value: "琼中",
			text: "琼中",
			zipcode: "469036"
		}, {
			value: "西沙",
			text: "西沙",
			zipcode: "469037"
		}, {
			value: "南沙",
			text: "南沙",
			zipcode: "469038"
		}, {
			value: "中沙",
			text: "中沙",
			zipcode: "469039"
		}],
		zipcode: "460000"
	}, {
		value: "重庆",
		text: "重庆",
		children: [{
			value: "万州",
			text: "万州",
			zipcode: "500101"
		}, {
			value: "涪陵",
			text: "涪陵",
			zipcode: "500102"
		}, {
			value: "渝中",
			text: "渝中",
			zipcode: "500103"
		}, {
			value: "大渡口",
			text: "大渡口",
			zipcode: "500104"
		}, {
			value: "江北",
			text: "江北",
			zipcode: "500105"
		}, {
			value: "沙坪坝",
			text: "沙坪坝",
			zipcode: "500106"
		}, {
			value: "九龙坡",
			text: "九龙坡",
			zipcode: "500107"
		}, {
			value: "南岸",
			text: "南岸",
			zipcode: "500108"
		}, {
			value: "北碚",
			text: "北碚",
			zipcode: "500109"
		}, {
			value: "万盛",
			text: "万盛",
			zipcode: "500110"
		}, {
			value: "双桥",
			text: "双桥",
			zipcode: "500111"
		}, {
			value: "渝北",
			text: "渝北",
			zipcode: "500112"
		}, {
			value: "巴南",
			text: "巴南",
			zipcode: "500113"
		}, {
			value: "黔江",
			text: "黔江",
			zipcode: "500114"
		}, {
			value: "长寿",
			text: "长寿",
			zipcode: "500115"
		}, {
			value: "綦江",
			text: "綦江",
			zipcode: "500222"
		}, {
			value: "潼南",
			text: "潼南",
			zipcode: "500223"
		}, {
			value: "铜梁",
			text: "铜梁",
			zipcode: "500224"
		}, {
			value: "大足",
			text: "大足",
			zipcode: "500225"
		}, {
			value: "荣昌",
			text: "荣昌",
			zipcode: "500226"
		}, {
			value: "璧山",
			text: "璧山",
			zipcode: "500227"
		}, {
			value: "梁平",
			text: "梁平",
			zipcode: "500228"
		}, {
			value: "城口",
			text: "城口",
			zipcode: "500229"
		}, {
			value: "丰都",
			text: "丰都",
			zipcode: "500230"
		}, {
			value: "垫江",
			text: "垫江",
			zipcode: "500231"
		}, {
			value: "武隆",
			text: "武隆",
			zipcode: "500232"
		}, {
			value: "忠县",
			text: "忠县",
			zipcode: "500233"
		}, {
			value: "开县",
			text: "开县",
			zipcode: "500234"
		}, {
			value: "云阳",
			text: "云阳",
			zipcode: "500235"
		}, {
			value: "奉节",
			text: "奉节",
			zipcode: "500236"
		}, {
			value: "巫山",
			text: "巫山",
			zipcode: "500237"
		}, {
			value: "巫溪",
			text: "巫溪",
			zipcode: "500238"
		}, {
			value: "石柱",
			text: "石柱",
			zipcode: "500240"
		}, {
			value: "秀山",
			text: "秀山",
			zipcode: "500241"
		}, {
			value: "酉阳",
			text: "酉阳",
			zipcode: "500242"
		}, {
			value: "彭水",
			text: "彭水",
			zipcode: "500243"
		}, {
			value: "江津",
			text: "江津",
			zipcode: "500381"
		}, {
			value: "合川",
			text: "合川",
			zipcode: "500382"
		}, {
			value: "永川",
			text: "永川",
			zipcode: "500383"
		}, {
			value: "南川",
			text: "南川",
			zipcode: "500384"
		}, {
			value: "两江新区",
			text: "两江新区",
			zipcode: "500385"
		}],
		zipcode: "500000"
	}, {
		value: "四川",
		text: "四川",
		children: [{
			value: "成都",
			text: "成都",
			zipcode: "510100"
		}, {
			value: "自贡",
			text: "自贡",
			zipcode: "510300"
		}, {
			value: "攀枝花",
			text: "攀枝花",
			zipcode: "510400"
		}, {
			value: "泸州",
			text: "泸州",
			zipcode: "510500"
		}, {
			value: "德阳",
			text: "德阳",
			zipcode: "510600"
		}, {
			value: "绵阳",
			text: "绵阳",
			zipcode: "510700"
		}, {
			value: "广元",
			text: "广元",
			zipcode: "510800"
		}, {
			value: "遂宁",
			text: "遂宁",
			zipcode: "510900"
		}, {
			value: "内江",
			text: "内江",
			zipcode: "511000"
		}, {
			value: "乐山",
			text: "乐山",
			zipcode: "511100"
		}, {
			value: "南充",
			text: "南充",
			zipcode: "511300"
		}, {
			value: "眉山",
			text: "眉山",
			zipcode: "511400"
		}, {
			value: "宜宾",
			text: "宜宾",
			zipcode: "511500"
		}, {
			value: "广安",
			text: "广安",
			zipcode: "511600"
		}, {
			value: "达州",
			text: "达州",
			zipcode: "511700"
		}, {
			value: "雅安",
			text: "雅安",
			zipcode: "511800"
		}, {
			value: "巴中",
			text: "巴中",
			zipcode: "511900"
		}, {
			value: "资阳",
			text: "资阳",
			zipcode: "512000"
		}, {
			value: "阿坝",
			text: "阿坝",
			zipcode: "513200"
		}, {
			value: "甘孜",
			text: "甘孜",
			zipcode: "513300"
		}, {
			value: "凉山",
			text: "凉山",
			zipcode: "513400"
		}],
		zipcode: "510000"
	}, {
		value: "贵州",
		text: "贵州",
		children: [{
			value: "贵阳",
			text: "贵阳",
			zipcode: "520100"
		}, {
			value: "六盘水",
			text: "六盘水",
			zipcode: "520200"
		}, {
			value: "遵义",
			text: "遵义",
			zipcode: "520300"
		}, {
			value: "安顺",
			text: "安顺",
			zipcode: "520400"
		}, {
			value: "铜仁",
			text: "铜仁",
			zipcode: "522200"
		}, {
			value: "黔西南",
			text: "黔西南",
			zipcode: "522300"
		}, {
			value: "毕节",
			text: "毕节",
			zipcode: "522400"
		}, {
			value: "黔东南",
			text: "黔东南",
			zipcode: "522600"
		}, {
			value: "黔南布",
			text: "黔南布",
			zipcode: "522700"
		}],
		zipcode: "520000"
	}, {
		value: "云南",
		text: "云南",
		children: [{
			value: "昆明",
			text: "昆明",
			zipcode: "530100"
		}, {
			value: "曲靖",
			text: "曲靖",
			zipcode: "530300"
		}, {
			value: "玉溪",
			text: "玉溪",
			zipcode: "530400"
		}, {
			value: "保山",
			text: "保山",
			zipcode: "530500"
		}, {
			value: "昭通",
			text: "昭通",
			zipcode: "530600"
		}, {
			value: "丽江",
			text: "丽江",
			zipcode: "530700"
		}, {
			value: "普洱",
			text: "普洱",
			zipcode: "530800"
		}, {
			value: "临沧",
			text: "临沧",
			zipcode: "530900"
		}, {
			value: "楚雄",
			text: "楚雄",
			zipcode: "532300"
		}, {
			value: "红河",
			text: "红河",
			zipcode: "532500"
		}, {
			value: "文山",
			text: "文山",
			zipcode: "532600"
		}, {
			value: "西双版纳",
			text: "西双版纳",
			zipcode: "532800"
		}, {
			value: "大理",
			text: "大理",
			zipcode: "532900"
		}, {
			value: "德宏",
			text: "德宏",
			zipcode: "533100"
		}, {
			value: "怒江",
			text: "怒江",
			zipcode: "533300"
		}, {
			value: "迪庆",
			text: "迪庆",
			zipcode: "533400"
		}],
		zipcode: "530000"
	}, {
		value: "西藏",
		text: "西藏",
		children: [{
			value: "拉萨",
			text: "拉萨",
			zipcode: "540100"
		}, {
			value: "昌都",
			text: "昌都",
			zipcode: "542100"
		}, {
			value: "山南",
			text: "山南",
			zipcode: "542200"
		}, {
			value: "日喀则",
			text: "日喀则",
			zipcode: "542300"
		}, {
			value: "那曲",
			text: "那曲",
			zipcode: "542400"
		}, {
			value: "阿里",
			text: "阿里",
			zipcode: "542500"
		}, {
			value: "林芝",
			text: "林芝",
			zipcode: "542600"
		}],
		zipcode: "540000"
	}, {
		value: "陕西",
		text: "陕西",
		children: [{
			value: "西安",
			text: "西安",
			zipcode: "610100"
		}, {
			value: "铜川",
			text: "铜川",
			zipcode: "610200"
		}, {
			value: "宝鸡",
			text: "宝鸡",
			zipcode: "610300"
		}, {
			value: "咸阳",
			text: "咸阳",
			zipcode: "610400"
		}, {
			value: "渭南",
			text: "渭南",
			zipcode: "610500"
		}, {
			value: "延安",
			text: "延安",
			zipcode: "610600"
		}, {
			value: "汉中",
			text: "汉中",
			zipcode: "610700"
		}, {
			value: "榆林",
			text: "榆林",
			zipcode: "610800"
		}, {
			value: "安康",
			text: "安康",
			zipcode: "610900"
		}, {
			value: "商洛",
			text: "商洛",
			zipcode: "611000"
		}],
		zipcode: "610000"
	}, {
		value: "甘肃",
		text: "甘肃",
		children: [{
			value: "兰州",
			text: "兰州",
			zipcode: "620100"
		}, {
			value: "嘉峪关",
			text: "嘉峪关",
			zipcode: "620200"
		}, {
			value: "金昌",
			text: "金昌",
			zipcode: "620300"
		}, {
			value: "白银",
			text: "白银",
			zipcode: "620400"
		}, {
			value: "天水",
			text: "天水",
			zipcode: "620500"
		}, {
			value: "武威",
			text: "武威",
			zipcode: "620600"
		}, {
			value: "张掖",
			text: "张掖",
			zipcode: "620700"
		}, {
			value: "平凉",
			text: "平凉",
			zipcode: "620800"
		}, {
			value: "酒泉",
			text: "酒泉",
			zipcode: "620900"
		}, {
			value: "庆阳",
			text: "庆阳",
			zipcode: "621000"
		}, {
			value: "定西",
			text: "定西",
			zipcode: "621100"
		}, {
			value: "陇南",
			text: "陇南",
			zipcode: "621200"
		}, {
			value: "临夏",
			text: "临夏",
			zipcode: "622900"
		}, {
			value: "甘南",
			text: "甘南",
			zipcode: "623000"
		}],
		zipcode: "620000"
	}, {
		value: "青海",
		text: "青海",
		children: [{
			value: "西宁",
			text: "西宁",
			zipcode: "630100"
		}, {
			value: "海东",
			text: "海东",
			zipcode: "632100"
		}, {
			value: "海北",
			text: "海北",
			zipcode: "632200"
		}, {
			value: "黄南",
			text: "黄南",
			zipcode: "632300"
		}, {
			value: "海南",
			text: "海南",
			zipcode: "632500"
		}, {
			value: "果洛",
			text: "果洛",
			zipcode: "632600"
		}, {
			value: "玉树",
			text: "玉树",
			zipcode: "632700"
		}, {
			value: "海西",
			text: "海西",
			zipcode: "632800"
		}],
		zipcode: "630000"
	}, {
		value: "宁夏",
		text: "宁夏",
		children: [{
			value: "银川",
			text: "银川",
			zipcode: "640100"
		}, {
			value: "石嘴山",
			text: "石嘴山",
			zipcode: "640200"
		}, {
			value: "吴忠",
			text: "吴忠",
			zipcode: "640300"
		}, {
			value: "固原",
			text: "固原",
			zipcode: "640400"
		}, {
			value: "中卫",
			text: "中卫",
			zipcode: "640500"
		}],
		zipcode: "640000"
	}, {
		value: "新疆",
		text: "新疆",
		children: [{
			value: "乌鲁木齐",
			text: "乌鲁木齐",
			zipcode: "650100"
		}, {
			value: "克拉玛依",
			text: "克拉玛依",
			zipcode: "650200"
		}, {
			value: "吐鲁番",
			text: "吐鲁番",
			zipcode: "652100"
		}, {
			value: "哈密地区",
			text: "哈密地区",
			zipcode: "652200"
		}, {
			value: "昌吉",
			text: "昌吉",
			zipcode: "652300"
		}, {
			value: "博尔塔拉",
			text: "博尔塔拉",
			zipcode: "652700"
		}, {
			value: "巴音郭楞",
			text: "巴音郭楞",
			zipcode: "652800"
		}, {
			value: "阿克苏",
			text: "阿克苏",
			zipcode: "652900"
		}, {
			value: "克孜勒苏",
			text: "克孜勒苏",
			zipcode: "653000"
		}, {
			value: "喀什",
			text: "喀什",
			zipcode: "653100"
		}, {
			value: "和田",
			text: "和田",
			zipcode: "653200"
		}, {
			value: "伊犁",
			text: "伊犁",
			zipcode: "654000"
		}, {
			value: "塔城",
			text: "塔城",
			zipcode: "654200"
		}, {
			value: "阿勒泰",
			text: "阿勒泰",
			zipcode: "654300"
		}, {
			value: "石河子",
			text: "石河子",
			zipcode: "659001"
		}, {
			value: "阿拉尔",
			text: "阿拉尔",
			zipcode: "659002"
		}, {
			value: "图木舒克",
			text: "图木舒克",
			zipcode: "659003"
		}, {
			value: "五家渠",
			text: "五家渠",
			zipcode: "659004"
		}],
		zipcode: "650000"
	}, {
		value: "台湾",
		text: "台湾",
		children: [{
			value: "台北市",
			text: "台北市",
			zipcode: "710100"
		}, {
			value: "高雄市",
			text: "高雄市",
			zipcode: "710200"
		}, {
			value: "台南市",
			text: "台南市",
			zipcode: "710300"
		}, {
			value: "台中市",
			text: "台中市",
			zipcode: "710400"
		}, {
			value: "金门县",
			text: "金门县",
			zipcode: "710500"
		}, {
			value: "南投县",
			text: "南投县",
			zipcode: "710600"
		}, {
			value: "基隆市",
			text: "基隆市",
			zipcode: "710700"
		}, {
			value: "新竹市",
			text: "新竹市",
			zipcode: "710800"
		}, {
			value: "嘉义市",
			text: "嘉义市",
			zipcode: "710900"
		}, {
			value: "新北市",
			text: "新北市",
			zipcode: "711100"
		}, {
			value: "宜兰县",
			text: "宜兰县",
			zipcode: "711200"
		}, {
			value: "新竹县",
			text: "新竹县",
			zipcode: "711300"
		}, {
			value: "桃园县",
			text: "桃园县",
			zipcode: "711400"
		}, {
			value: "苗栗县",
			text: "苗栗县",
			zipcode: "711500"
		}, {
			value: "彰化县",
			text: "彰化县",
			zipcode: "711700"
		}, {
			value: "嘉义县",
			text: "嘉义县",
			zipcode: "711900"
		}, {
			value: "云林县",
			text: "云林县",
			zipcode: "712100"
		}, {
			value: "屏东县",
			text: "屏东县",
			zipcode: "712400"
		}, {
			value: "台东县",
			text: "台东县",
			zipcode: "712500"
		}, {
			value: "花莲县",
			text: "花莲县",
			zipcode: "712600"
		}, {
			value: "澎湖县",
			text: "澎湖县",
			zipcode: "712700"
		}],
		zipcode: "710000"
	}, {
		value: "香港",
		text: "香港",
		children: [{
			value: "香港岛",
			text: "香港岛",
			zipcode: "810100"
		}, {
			value: "九龙",
			text: "九龙",
			zipcode: "810200"
		}, {
			value: "新界",
			text: "新界",
			zipcode: "810300"
		}],
		zipcode: "810000"
	}, {
		value: "澳门",
		text: "澳门",
		children: [{
			value: "澳门半岛",
			text: "澳门半岛",
			zipcode: "820100"
		}, {
			value: "离岛",
			text: "离岛",
			zipcode: "820200"
		}],
		zipcode: "820000"
	}, {
		value: "海外",
		text: "海外",
		children: [{
			value: "海外",
			text: "海外",
			zipcode: "990100"
		}],
		zipcode: "990000"
	}];